url_shortener/models.py
from .db import db
import string
from random import choices
from .db import db

class Url(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(200), unique=True)
    short_url = db.Column(db.String(16))
    visits = db.Column(db.Integer, default=0)



    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_url()
    
    def generate_short_url(self):
        characters =  string.digits + string.ascii_letters
        path = ''.join(choices(characters, k = 3))
        short_url = "{domain}{path} ".format(domain='wrlc.shrt', path = path)
        
        url = self.query.filter_by(short_url=short_url).first()
        
        if url:
            return self.generate_short_url()

        return short_url

class Stats(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(200))
    visits = db.Column(db.Integer, default=0)

   

url_shortener/__init__.py
from flask import Flask
from .db import db
from .routes import new_app


def create_app(config_file = 'settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    app.register_blueprint(new_app)
    
    return app

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .db import db
from .models import Url
import re

new_app = Blueprint('new_app', __name__)

@new_app.route('/<short_url>')
def redirect_to_url(short_url):
    url = Url.query.filter_by(short_url=short_url).first()
    
    return redirect(url.original_url)

@new_app.route('/')
def add_index():
    return render_template('index.html')

@new_app.route('/add_url', methods=['POST'])
def add_url():
    
    org_url =request.form['original_url']
    original = re.compile(r'https?://(www\.)?')
    original_url = original.sub('', org_url).strip().strip('/')

    url = Url.query.filter_by(original_url=original_url).first()
    if url:
        url.visits = url.visits + 1
    else:
        url = Url(original_url=original_url)
    
        db.session.add(url)
    db.session.commit()
    return render_template('url_added.html' , new_url = url.short_url, original_url = url.original_url)
    
@new_app.route('/visits', methods = ['POST'])
def visits():
    url = Url.query.all()
    return render_template('visit.html', urls=url)

url_shortener/templates/index.html
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}
.center{
    margin:auto;
    width: 25%;
    height:auto;
    border: 3px solid grey;
    padding: 10px;
    position:absolute;
    top: 50%;
    left: 40%;
    background-color:rgba(114, 121, 119, 0.911);

}

</style>
<body style="background-color:darkgrey;">
<div class = "center">
    
    <form method = "POST" action = "{{ url_for('new_app.add_url')}}" >
        <input type = "text" id = "url" name = "original_url" placeholder="Your Url" required/>
        <input type = "submit" id = "register" value="Submit" >
    </form>
    <form method = "Post" action = "{{ url_for('new_app.visits')}}">
        <input type = "submit" id = "register" value="Check Visit"/>
    </form>
</div>


</body>
</html>

url_shortener/templates/url_added.html
<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
.center{
    margin:auto;
    width: 25%;
    height:auto;
    border: 3px solid grey;
    padding: 30px;
    position:absolute;
    top: 50%;
    left: 35%;
    background-color:rgba(114, 121, 119, 0.911);

}
body{
    background: color grey;

}
</style>
</head>
<body style="background-color:darkgrey;">
    <div class = "color">
<div class = "center">
<table id="customers">
  <tr>
    <th>Original URL</th>
    <th>New Shortened URL</th>
    
    
  </tr>
  <tr>
    <td>{{ original_url}}</td>
    <td>{{ url_for('new_app.redirect_to_url', short_url=new_url )}}</td>
    
    </tr>
</table>
</div>
</div>

</body>
</html>

url_shortener/templates/visit.html
<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
.center{
    margin:auto;
    width: 25%;
    height:auto;
    border: 3px solid grey;
    padding: 30px;
    position:absolute;
    top: 50%;
    left: 35%;
    background-color:rgba(114, 121, 119, 0.911);

}
body{
    background: color grey;

}
</style>
</head>
<body style="background-color:darkgrey;">
    <div class = "color">
<div class = "center">
<table id="customers">
  <tr>
    <th>Original URL</th>
    <th>Visits</th>
    {% for url in urls %}
  </tr>
  <tr>
    <td> {{url.original_url }}</td>
    <td>{{url.visits}}</td>
    </tr>
    {% endfor %}
</table>
</div>
</div>

</body>
</html>